set target_triplet riscv32-unknown-elf

case "$target_triplet" in {

    { "riscv32-*-*" } {
        if {! [info exists target_list]} {
            set target_list { "riscv-sim" }
        }
    }

    { "riscv64-*-*" } {
        if {! [info exists target_list]} {
            set target_list { "riscv-sim" }
        }
    }

    default {
        error "Unknown target $target_triplet in site.exp"
    }
}
